# Generated by Django 2.2.6 on 2019-10-29 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
